#!/bin/sh

PATH=/bin:/usr/bin:/sbin:/usr/sbin
DAEMON=/usr/bin/piweb

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

case "$1" in
  start)
     log_daemon_msg "Starting PiWeb Server"
     #start_daemon $DAEMON start --deamon
     $DAEMON start --daemon
     log_end_msg $?
   ;;
  stop)
     log_daemon_msg "Stopping PiWeb Server"
     status=1
     [ -z "`$DAEMON stop | grep Error`" ] && status=0
     log_end_msg $status
   ;;
  force-reload|restart)
     $0 stop
     sleep 3
     $0 start
   ;;
 *)
   echo "Usage: /etc/init.d/atd {start|stop|restart|force-reload}"
   exit 1
  ;;
esac

exit 0
