# -*- coding: utf-8 -*-
# bookmark

bookmark:
    - name: Basic
      list:
        - title: Google
          link: http://www.google.com
          icon: true
        - title: Daum
          link: http://www.daum.net
          icon: true
        - title: Naver
          link: http://www.naver.com
          icon: true
